// Random reading results for palm and face modes
// Longer, more detailed analysis with multiple paragraphs

function seededRandom(seed: number): () => number {
  let s = seed;
  return () => {
    s = (s * 16807 + 0) % 2147483647;
    return (s - 1) / 2147483646;
  };
}

// FREE_SECTIONS: chỉ 2 section đầu hiển thị free, còn lại blur
export const FREE_SECTION_COUNT = 2;

const PALM_RESULTS = {
  overall: [
    'Theo như tôi phân tích, lòng bàn tay bạn cho thấy một người có nội lực mạnh mẽ và ý chí kiên cường. Các đường chỉ tay rõ ràng, sâu, cho thấy bạn có khả năng vượt qua khó khăn và đạt được mục tiêu trong cuộc sống.\n\nĐặc biệt, sự kết hợp giữa đường tâm đạo và trí đạo cho thấy bạn biết cách cân bằng giữa cảm xúc và lý trí. Đây là phẩm chất hiếm có, giúp bạn đưa ra quyết định đúng đắn trong những tình huống phức tạp nhất.\n\nCác đường phụ trên lòng bàn tay cũng cho thấy bạn đang trong giai đoạn chuyển đổi năng lượng tích cực. Trong 6 tháng tới, bạn sẽ cảm nhận rõ sự thay đổi này qua các cơ hội mới xuất hiện.',
    'Theo phân tích, bàn tay bạn thể hiện sự cân bằng tốt giữa lý trí và cảm xúc. Bạn là người biết cách quản lý cuộc sống và có tầm nhìn xa trong sự nghiệp lẫn tình cảm.\n\nĐiểm đặc biệt là các ngón tay cân đối, cho thấy bạn có khả năng đa nhiệm và thích ứng tốt với môi trường mới. Bạn không phải là người cố chấp — sẵn sàng thay đổi khi cần thiết, nhưng vẫn giữ vững nguyên tắc cốt lõi.\n\nNgoài ra, vùng gò tay dưới ngón áp út phát triển cho thấy bạn có khiếu nghệ thuật và thẩm mỹ. Đây có thể là một nguồn thu nhập phụ hoặc niềm vui trong cuộc sống.',
    'Theo như tôi phân tích, đường vân tay của bạn cho thấy năng lượng tích cực và may mắn đang bao quanh. Bạn có khả năng thu hút cơ hội tốt và biến chúng thành thành công.\n\nCác vân tay hình xoắn ốc (whorl) trên nhiều ngón cho thấy bạn là người độc đáo, có tư duy riêng và không dễ bị ảnh hưởng bởi đám đông. Đây là đặc điểm của những người tiên phong và đổi mới.\n\nTheo phân tích tổng thể, giai đoạn hiện tại của bạn đang ở trong chu kỳ tăng trưởng mạnh. Hãy tận dụng thời điểm này để khởi đầu những dự án quan trọng.',
    'Theo phân tích, lòng bàn tay bạn phản ánh một tâm hồn phong phú và trí tuệ sắc bén. Bạn có tiềm năng lớn trong nhiều lĩnh vực, đặc biệt là sáng tạo và giao tiếp.\n\nĐường trí đạo dài và sâu cho thấy khả năng tư duy logic vượt trội. Bạn có thể phân tích vấn đề phức tạp và tìm ra giải pháp mà người khác không nhìn thấy. Kết hợp với đường tâm đạo mạnh, bạn cũng rất nhạy cảm với cảm xúc của người khác.\n\nMột điều thú vị là các đường phụ xung quanh ngón cái cho thấy ý chí mạnh mẽ. Khi bạn đã quyết định điều gì, rất khó để ai thay đổi ý bạn. Đây vừa là điểm mạnh vừa là điều cần lưu ý.',
  ],
  love: [
    'Đường tâm đạo của bạn cho thấy bạn là người giàu cảm xúc, yêu sâu sắc và trung thành. Trong thời gian tới, mối quan hệ tình cảm sẽ có nhiều chuyển biến tích cực.\n\nĐặc biệt, độ cong của đường tâm đạo hướng về phía ngón trỏ cho thấy bạn là người lý tưởng hóa tình yêu, luôn tìm kiếm sự kết nối sâu sắc về tinh thần. Bạn không chỉ cần sự hấp dẫn thể chất mà còn cần sự đồng điệu về tâm hồn.\n\nCác đường nhánh nhỏ từ đường tâm đạo cho thấy bạn đã trải qua một số mối quan hệ có ý nghĩa. Mỗi mối quan hệ đều dạy bạn một bài học quý giá, giúp bạn trưởng thành hơn trong tình yêu. Giai đoạn sắp tới hứa hẹn sự ổn định và hạnh phúc.',
    'Theo như tôi phân tích, đường tình cảm của bạn thể hiện sự chân thành và khao khát yêu thương. Bạn có khả năng xây dựng mối quan hệ bền vững và ý nghĩa.\n\nĐiểm bắt đầu của đường tâm đạo ở vị trí cao cho thấy bạn đặt tiêu chuẩn cao trong tình yêu. Bạn không dễ rung động, nhưng một khi đã yêu thì rất sâu đậm và trọn vẹn.\n\nCác dấu hiệu trên lòng bàn tay cũng gợi ý rằng bạn có thể gặp được "định mệnh" trong vòng 1-2 năm tới. Hãy mở lòng và tham gia nhiều hoạt động xã hội hơn để tăng cơ hội.',
    'Đường tâm đạo dài và rõ ràng cho thấy bạn là người lãng mạn nhưng cũng rất thực tế trong tình yêu. Hạnh phúc đang chờ đón bạn nếu mở lòng đón nhận.\n\nĐộ sâu của đường tâm đạo cho thấy cường độ cảm xúc mạnh mẽ. Bạn yêu hết mình và cũng đau hết mình. Tuy nhiên, sự trưởng thành cảm xúc giúp bạn biết cách bảo vệ trái tim mà không trở nên phòng thủ.\n\nTheo phân tích, giai đoạn tới đây là thời điểm vàng cho tình yêu. Nếu đang trong mối quan hệ, sẽ có bước tiến mới (đính hôn, kết hôn, con cái). Nếu độc thân, cơ hội gặp người phù hợp rất cao.',
    'Theo phân tích, vân tay cho thấy bạn sẽ gặp được người phù hợp trong tương lai gần. Hãy kiên nhẫn và tin tưởng vào duyên phận.\n\nĐường tâm đạo có nhánh hướng xuống cho thấy bạn là người có thiên hướng bảo bọc và chăm sóc trong tình yêu. Đối phương sẽ cảm thấy an toàn và được yêu thương khi ở bên bạn.\n\nMột chi tiết thú vị: các đường nhỏ song song với đường tâm đạo cho thấy bạn có khả năng duy trì nhiều mối quan hệ thân thiết (bạn bè, gia đình, tình yêu) cùng lúc mà vẫn giữ được sự cân bằng.',
  ],
  career: [
    'Đường sự nghiệp của bạn cho thấy tiềm năng phát triển mạnh mẽ. Bạn có tố chất lãnh đạo và khả năng ra quyết định tốt, phù hợp với các vị trí quản lý.\n\nĐường sự nghiệp bắt đầu từ cổ tay và chạy thẳng lên cho thấy con đường sự nghiệp rõ ràng từ sớm. Bạn biết mình muốn gì và sẵn sàng nỗ lực để đạt được. Đặc biệt, đường này không bị đứt đoạn cho thấy sự liên tục và ổn định trong công việc.\n\nCác đường phụ từ đường sự nghiệp hướng lên ngón trỏ cho thấy khả năng thăng tiến trong 3-5 năm tới. Bạn có thể đạt vị trí quản lý cấp cao hoặc thành công trong kinh doanh riêng.',
    'Theo như tôi phân tích, các đường chỉ tay liên quan đến sự nghiệp cho thấy bạn sẽ có những bước tiến đáng kể trong công việc. Cơ hội thăng tiến đang đến gần.\n\nĐiều đặc biệt là gò Mộc Tinh (dưới ngón trỏ) phát triển cho thấy bạn có khả năng lãnh đạo tự nhiên và tham vọng lớn. Bạn không chỉ muốn thành công cho bản thân mà còn muốn tạo ảnh hưởng tích cực đến cộng đồng.\n\nTheo phân tích tổng hợp, giai đoạn 2025-2028 sẽ là thời kỳ đỉnh cao trong sự nghiệp. Hãy chuẩn bị sẵn sàng về kiến thức, kỹ năng và mối quan hệ.',
    'Đường trí đạo kết hợp đường sự nghiệp cho thấy bạn phù hợp với công việc đòi hỏi sự sáng tạo và tư duy chiến lược. Lĩnh vực kinh doanh hoặc công nghệ sẽ mang lại thành công.\n\nĐường trí đạo dài vượt qua giữa lòng bàn tay cho thấy khả năng phân tích và tư duy chiến lược xuất sắc. Bạn nhìn thấy bức tranh lớn khi người khác chỉ thấy chi tiết nhỏ. Đây là phẩm chất quý giá trong quản lý và kinh doanh.\n\nCác đường giao cắt giữa trí đạo và sự nghiệp tại vùng giữa lòng bàn tay cho thấy khoảng tuổi 30-35 sẽ có bước ngoặt lớn. Có thể là thăng chức, chuyển ngành, hoặc khởi nghiệp.',
    'Theo phân tích, bàn tay bạn thể hiện sự đa tài và khả năng thích ứng cao. Bạn có thể thành công ở nhiều lĩnh vực khác nhau nếu tập trung và kiên trì.\n\nĐường sự nghiệp có nhánh cho thấy bạn có thể theo đuổi song song nhiều nguồn thu nhập. Không nhất thiết phải chọn một con đường duy nhất — sự đa dạng chính là sức mạnh của bạn.\n\nGò Kim Tinh (dưới ngón cái) phát triển cho thấy bạn có sức sống dồi dào và năng lượng để theo đuổi nhiều dự án. Tuy nhiên, cần học cách ưu tiên để không bị dàn trải quá mức.',
  ],
  health: [
    'Đường sinh đạo dài và rõ cho thấy sức khỏe tổng thể tốt và tuổi thọ cao. Tuy nhiên, cần chú ý đến giấc ngủ và stress trong thời gian tới để duy trì năng lượng.\n\nĐộ cong rộng của đường sinh đạo cho thấy sức sống mạnh mẽ và hệ miễn dịch tốt. Bạn có thể phục hồi nhanh sau bệnh tật và có sức chịu đựng cao hơn người bình thường.\n\nTuy nhiên, một số đường nhỏ cắt ngang đường sinh đạo cho thấy có những giai đoạn stress ảnh hưởng đến sức khỏe. Đặc biệt cần chú ý vào khoảng tuổi 35-40, nên kiểm tra sức khỏe định kỳ và duy trì lối sống lành mạnh.',
    'Theo như tôi phân tích, đường sức khỏe cho thấy thể trạng ổn định nhưng cần duy trì thói quen tập luyện đều đặn và ăn uống cân bằng để phát huy tối đa sức khỏe.\n\nĐường sinh đạo bắt đầu gần đường trí đạo cho thấy sức khỏe tinh thần ảnh hưởng lớn đến thể chất. Khi bạn vui vẻ và lạc quan, cơ thể cũng khỏe mạnh hơn. Ngược lại, stress và lo âu có thể gây ra các vấn đề về dạ dày và đau đầu.\n\nLời khuyên: tập thiền hoặc yoga ít nhất 3 lần/tuần, uống 2-3 lít nước mỗi ngày, và ngủ trước 11 giờ đêm. Những thói quen đơn giản này sẽ tạo ra sự khác biệt lớn.',
    'Đường sinh đạo của bạn gợi ý nên chú ý hơn đến sức khỏe tinh thần. Thiền định, yoga hoặc các hoạt động thư giãn sẽ rất có lợi cho bạn.\n\nCác đường nhánh từ đường sinh đạo hướng lên trên cho thấy bạn có khả năng phục hồi tốt. Tuy nhiên, xu hướng làm việc quá sức có thể dẫn đến kiệt sức (burnout) nếu không biết giới hạn.\n\nĐặc biệt, vùng gò Thủy Tinh (dưới ngón út) hơi phẳng cho thấy cần bổ sung thêm các hoạt động giải trí và thư giãn. Đừng để công việc chiếm hết thời gian — sức khỏe là tài sản quý giá nhất.',
    'Theo phân tích, vân tay cho thấy bạn có hệ miễn dịch tốt nhưng cần chú ý bảo vệ hệ tiêu hóa và cột sống. Chế độ ăn nhiều rau xanh và tập thể dục đều đặn là điều cần thiết.\n\nĐường sinh đạo có hình dáng cân đối cho thấy bạn có gen di truyền tốt về sức khỏe. Tuy nhiên, lối sống hiện đại (ngồi nhiều, ăn đồ chế biến) có thể làm giảm lợi thế tự nhiên này.\n\nTheo phân tích, giai đoạn 30-45 tuổi cần đặc biệt chú ý sức khỏe. Hãy xây dựng thói quen tốt từ bây giờ: tập luyện 30 phút mỗi ngày, ăn 5 phần rau quả, và kiểm tra sức khỏe tổng quát hàng năm.',
  ],
  personality: [
    'Theo như tôi phân tích, bàn tay bạn cho thấy tính cách mạnh mẽ, quyết đoán nhưng cũng rất tinh tế. Bạn có khả năng đồng cảm cao và biết cách lắng nghe người khác.\n\nHình dáng các ngón tay cho thấy bạn là người kết hợp giữa thực tế và trực giác. Ngón trỏ dài cho thấy tham vọng lớn, ngón giữa cân đối cho thấy sự cân bằng, ngón áp út phát triển cho thấy khiếu nghệ thuật.\n\nĐặc biệt, đường trí đạo của bạn cho thấy khả năng tập trung cao và tư duy logic mạnh. Bạn thích phân tích vấn đề đến tận gốc rễ thay vì chỉ nhìn bề mặt. Đây là phẩm chất của những nhà nghiên cứu, chiến lược gia và doanh nhân thành công.',
    'Đường trí đạo cho thấy bạn là người thông minh, logic và có tư duy phân tích tốt. Bạn thích học hỏi và luôn tìm cách cải thiện bản thân.\n\nKhoảng cách giữa đường trí đạo và đường tâm đạo ở vị trí bắt đầu cho thấy mức độ độc lập trong suy nghĩ. Bạn không dễ bị ảnh hưởng bởi ý kiến đám đông và có lập trường riêng rõ ràng.\n\nCác vân tay trên ngón cái (dạng vòng cung) cho thấy bạn là người thực tế, chân thành và đáng tin cậy. Mọi người xung quanh thường tìm đến bạn để xin lời khuyên vì họ biết bạn luôn nói thật.',
    'Theo phân tích, vân tay phản ánh một người có cá tính mạnh, sáng tạo và không ngại thử thách. Bạn có khả năng truyền cảm hứng cho người xung quanh.\n\nĐường trí đạo cong hướng xuống cho thấy trí tưởng tượng phong phú và khả năng sáng tạo vượt trội. Bạn nhìn thế giới qua lăng kính riêng, luôn tìm thấy vẻ đẹp và khả năng ở nơi người khác không thấy.\n\nSự kết hợp giữa đường trí đạo mạnh và gò Kim Tinh phát triển cho thấy bạn vừa sáng tạo vừa có năng lượng để biến ý tưởng thành hiện thực. Đây là điểm khác biệt — nhiều người có ý tưởng nhưng thiếu động lực thực hiện.',
    'Bàn tay bạn thể hiện sự kết hợp tốt giữa lý trí và trực giác. Bạn có khả năng đánh giá tình huống nhanh chóng và đưa ra quyết định đúng đắn.\n\nĐặc biệt, ngón cái linh hoạt cho thấy sự thích ứng cao — bạn dễ dàng hòa nhập vào mọi môi trường. Tuy nhiên, khi cần, bạn vẫn giữ vững lập trường và không dễ bị lung lay.\n\nCác đường phụ trên gò Sao Hỏa (giữa lòng bàn tay) cho thấy bạn có tinh thần chiến đấu mạnh mẽ. Bạn không bỏ cuộc dễ dàng và thường biến thất bại thành bài học quý giá.',
  ],
  future: [
    'Theo như tôi phân tích, các đường chỉ tay cho thấy tương lai sáng lạn đang chờ đợi bạn. Những nỗ lực hiện tại sẽ đem lại quả ngọt trong 2-3 năm tới.\n\nĐường vận mệnh mạnh và liên tục cho thấy bạn đang đi đúng hướng. Không có dấu hiệu của sự gián đoạn lớn — mọi thứ sẽ tiến triển từ từ nhưng chắc chắn.\n\nĐặc biệt, các đường hỗ trợ xung quanh đường vận mệnh cho thấy bạn sẽ có quý nhân phù trợ trong giai đoạn quan trọng. Hãy xây dựng và duy trì các mối quan hệ tốt đẹp — chúng sẽ là chìa khóa cho thành công tương lai.',
    'Đường vận mệnh cho thấy giai đoạn tới đây sẽ có nhiều thay đổi tích cực. Hãy sẵn sàng đón nhận cơ hội mới và dám mạo hiểm.\n\nCác nhánh từ đường vận mệnh hướng về phía ngón trỏ cho thấy cơ hội trong lĩnh vực quyền lực và lãnh đạo. Bạn có thể được mời đảm nhận vị trí quan trọng hơn hoặc khởi nghiệp thành công.\n\nThời điểm quan trọng nhất là khoảng 2-4 năm tới. Theo phân tích, đây là lúc các nỗ lực tích lũy sẽ chín muồi và mang lại kết quả xứng đáng. Hãy kiên nhẫn và tiếp tục đầu tư.',
    'Theo phân tích, vân tay gợi ý rằng bạn sẽ có bước ngoặt quan trọng trong sự nghiệp vào thời gian tới. Tài chính cũng sẽ ổn định và tăng trưởng.\n\nCác đường ngang trên cổ tay (vòng tay) cho thấy cuộc sống về sau sẽ sung túc. Đặc biệt, vòng thứ hai rõ ràng cho thấy sức khỏe tốt và tuổi thọ cao. Bạn có thể an tâm rằng nền tảng sức khỏe sẽ hỗ trợ bạn theo đuổi mục tiêu lâu dài.\n\nMột chi tiết đáng chú ý: đường di chuyển (travel lines) trên gò Mặt Trăng cho thấy bạn có thể có cơ hội đi nước ngoài hoặc làm việc với đối tác quốc tế trong tương lai gần.',
    'Các đường chỉ tay cho thấy bạn có tiềm năng lớn chưa được khai phá. Tương lai sẽ mang đến nhiều cơ hội để bạn thể hiện và phát triển bản thân.\n\nĐường vận mệnh có xu hướng mạnh dần về phía trên cho thấy cuộc sống sẽ ngày càng tốt hơn theo thời gian. Khác với nhiều người có đỉnh cao sớm rồi giảm dần, bạn thuộc dạng "muộn mà mạnh" — thành công lớn nhất đến trong nửa sau cuộc đời.\n\nCác đường hỗ trợ cho thấy bạn sẽ xây dựng được di sản lâu dài — không chỉ về tài chính mà còn về ảnh hưởng xã hội. Hãy bắt đầu nghĩ về việc bạn muốn để lại gì cho thế giới.',
  ],
};

const FACE_RESULTS = {
  overall: [
    'Theo như tôi phân tích, khuôn mặt bạn thể hiện tướng mạo phúc hậu, có quý nhân phù trợ. Tam đình (trán, mũi, cằm) cân đối cho thấy cuộc sống sẽ thuận lợi qua các giai đoạn.\n\nThượng đình (trán) rộng và sáng cho thấy tuổi trẻ được giáo dục tốt và có nền tảng vững chắc. Trung đình (mũi) cân đối cho thấy trung niên sự nghiệp phát triển thuận lợi. Hạ đình (cằm) đầy đặn hứa hẹn tuổi già an nhàn.\n\nNgũ quan (mắt, mũi, miệng, tai, lông mày) hài hòa tạo nên tổng thể cân bằng, phản ánh phúc phần và may mắn tự nhiên. Đây là tướng mạo mà nhiều người mong ước.',
    'Theo phân tích, ngũ quan hài hòa, tỷ lệ khuôn mặt cân xứng cho thấy bạn là người có phước phần và may mắn trong cuộc sống.\n\nĐặc biệt, khoảng cách giữa hai mắt phù hợp cho thấy bạn có tầm nhìn rộng và khả năng bao quát tình huống. Bạn không phải là người nhìn gần mà luôn có cái nhìn dài hạn và chiến lược.\n\nXương gò má ở vị trí phù hợp cho thấy bạn có quyền lực và ảnh hưởng tự nhiên. Mọi người tôn trọng ý kiến của bạn và thường tìm đến bạn khi cần lời khuyên.',
    'Khuôn mặt bạn toát lên sự thông minh và năng động. Theo như tôi phân tích, các đặc điểm tướng mặt cho thấy bạn sẽ thành công nhờ nỗ lực và trí tuệ.\n\nÁnh mắt sáng và linh hoạt là dấu hiệu của trí thông minh và khả năng nắm bắt cơ hội nhanh. Bạn thuộc dạng "mắt tinh, tay nhanh" — nhìn thấy cơ hội trước người khác và hành động ngay.\n\nThêm vào đó, sống mũi thẳng và cân đối cho thấy sự nghiệp phát triển thuận lợi trong giai đoạn trung niên (35-50 tuổi). Đây là giai đoạn mà bạn gặt hái nhiều thành quả nhất.',
    'Theo phân tích, tướng mạo của bạn thể hiện sự cân bằng giữa phúc đức và tài năng, mang lại nhiều thuận lợi trong cả sự nghiệp lẫn đời sống.\n\nKhuôn mặt có hình dáng cân đối giữa phần trên và phần dưới cho thấy sự hài hòa giữa lý trí và cảm xúc. Bạn biết khi nào cần quyết đoán và khi nào cần mềm mỏng — đây là phẩm chất của người lãnh đạo giỏi.\n\nĐường viền hàm rõ ràng cho thấy ý chí mạnh mẽ và khả năng kiên trì. Bạn không dễ bỏ cuộc và thường đạt được mục tiêu nhờ sự bền bỉ.',
  ],
  love: [
    'Theo như tôi phân tích, đôi mắt sáng và sống mũi thẳng cho thấy bạn là người chung thủy và có duyên trong tình cảm. Nhân duyên tốt đang chờ đón bạn.\n\nĐôi mắt to và trong sáng là dấu hiệu của sự chân thành trong tình yêu. Bạn yêu bằng cả trái tim và không giỏi giấu diếm cảm xúc. Đây vừa là điểm mạnh (đối phương cảm nhận được sự thật lòng) vừa là điểm yếu (dễ bị tổn thương).\n\nNhân trung (rãnh từ mũi đến môi trên) rõ ràng cho thấy phúc phần con cái tốt. Nếu bạn mong muốn xây dựng gia đình, tướng mạo cho thấy cuộc sống gia đình sẽ hạnh phúc và con cái ngoan.',
    'Khuôn miệng và cằm cho thấy bạn là người biết yêu thương và quan tâm người khác. Theo phân tích, mối quan hệ tình cảm sẽ ngày càng bền chặt.\n\nMôi đầy đặn và cân đối cho thấy bạn là người biết cách thể hiện tình cảm và tận hưởng cuộc sống. Bạn không ngại thể hiện tình yêu qua lời nói và hành động.\n\nGò má hơi hồng tự nhiên cho thấy bạn có sức hút lãng mạn. Người khác giới thường bị cuốn hút bởi sự ấm áp và dịu dàng tỏa ra từ bạn.',
    'Theo như tôi phân tích, tướng mặt cho thấy bạn có phúc phần trong đường tình duyên. Hôn nhân hạnh phúc và con cái hiếu thảo.\n\nLông mày cong đều và mịn cho thấy bạn là người tinh tế trong tình yêu, biết cách chăm sóc và giữ lửa cho mối quan hệ. Bạn không phải dạng yêu mãnh liệt rồi nhanh chán, mà là dạng tình yêu bền bỉ, sâu lắng.\n\nVùng quanh mắt sáng sủa (không quầng thâm, không nếp nhăn sớm) cho thấy đời sống tình cảm ổn định. Nếu hiện tại đang gặp khó khăn trong tình yêu, hãy yên tâm — đây chỉ là giai đoạn tạm thời.',
    'Đặc điểm khuôn mặt cho thấy bạn thu hút người khác bằng sự chân thành. Tình yêu đến một cách tự nhiên khi bạn là chính mình.\n\nĐôi mắt có ánh nhìn ấm áp cho thấy bạn là người có EQ (trí tuệ cảm xúc) cao. Bạn hiểu được cảm xúc của đối phương mà không cần họ nói ra — đây là phẩm chất quý giá trong mối quan hệ.\n\nTướng tai dày và gần đầu cho thấy bạn là người biết lắng nghe — yếu tố quan trọng nhất trong tình yêu lâu dài. Đối phương sẽ luôn cảm thấy được thấu hiểu khi ở bên bạn.',
  ],
  career: [
    'Trán rộng và cao cho thấy bạn có trí tuệ và tầm nhìn xa. Theo như tôi phân tích, sự nghiệp sẽ phát triển mạnh mẽ nhờ khả năng lãnh đạo thiên bẩm.\n\nTrán cao và không bị che bởi tóc mái cho thấy sự tự tin và minh bạch trong tư duy. Bạn phù hợp với các vị trí đòi hỏi ra quyết định chiến lược — CEO, quản lý cấp cao, hoặc chuyên gia tư vấn.\n\nXương gò má cao và cân đối cho thấy quyền lực và sự ủng hộ từ cấp dưới. Bạn là dạng lãnh đạo được yêu mến chứ không phải bị sợ hãi — đây là phong cách quản lý hiệu quả nhất.',
    'Theo phân tích, xương gò má và hàm cho thấy bạn có nghị lực và sự kiên trì. Thành công trong sự nghiệp là điều chắc chắn nếu bạn giữ vững quyết tâm.\n\nĐường viền hàm rõ ràng cho thấy ý chí sắt đá. Bạn không phải dạng dễ bỏ cuộc — khi gặp khó khăn, bạn càng cố gắng hơn. Đặc điểm này cực kỳ quan trọng trong kinh doanh và sự nghiệp.\n\nMũi thẳng và cánh mũi gọn cho thấy bạn biết cách quản lý tài chính và đầu tư. Bạn chi tiêu có kế hoạch và biết cách tạo ra giá trị từ nguồn lực có hạn.',
    'Tướng mạo cho thấy bạn phù hợp với công việc đòi hỏi sự giao tiếp và sáng tạo. Theo như tôi phân tích, lĩnh vực kinh doanh, truyền thông, giải trí sẽ rất phù hợp.\n\nMiệng rộng vừa phải cho thấy khả năng ăn nói và thuyết phục tự nhiên. Bạn có thể trở thành diễn giả, MC, hoặc nhà đàm phán giỏi. Kỹ năng giao tiếp là vũ khí bí mật của bạn.\n\nĐôi mắt linh hoạt cho thấy khả năng nắm bắt xu hướng nhanh. Bạn phù hợp với các ngành thay đổi nhanh như công nghệ, truyền thông số, hoặc marketing.',
    'Theo phân tích, ánh mắt sáng và tướng trán cho thấy bạn có khả năng tập trung cao. Điều này giúp bạn vượt trội trong các lĩnh vực chuyên môn.\n\nTrán hơi gồ ở vùng giữa cho thấy khả năng nghiên cứu và phân tích sâu. Bạn phù hợp với công việc đòi hỏi chuyên môn cao — bác sĩ, kỹ sư, nhà khoa học, hoặc chuyên gia tài chính.\n\nTai có vành tai rõ ràng cho thấy bạn học hỏi nhanh và nhớ lâu. Kiến thức tích lũy sẽ trở thành lợi thế cạnh tranh lớn nhất của bạn trong sự nghiệp.',
  ],
  health: [
    'Theo như tôi phân tích, sắc mặt tươi sáng cho thấy sức khỏe tốt. Tuy nhiên nên chú ý nghỉ ngơi đầy đủ để duy trì năng lượng và sức đề kháng.\n\nMắt sáng, tròng trắng sạch cho thấy gan và thận hoạt động tốt. Tuy nhiên, nếu thường xuyên thức khuya, các chỉ số này có thể suy giảm. Hãy ngủ trước 11 giờ đêm để bảo vệ sức khỏe.\n\nMôi hồng tự nhiên cho thấy hệ tuần hoàn máu tốt. Tuy nhiên, vùng dưới mắt hơi thâm cho thấy cần cải thiện giấc ngủ và giảm thời gian nhìn màn hình.',
    'Tướng mặt cho thấy thể trạng khỏe mạnh nhưng cần lưu ý về mắt và hệ hô hấp. Theo phân tích, nên tập thể dục đều đặn và tránh thức khuya.\n\nMũi thẳng và cánh mũi khỏe cho thấy hệ hô hấp tốt, nhưng cần chú ý khi thay đổi thời tiết. Uống nước ấm với mật ong và gừng vào buổi sáng sẽ giúp tăng cường sức đề kháng.\n\nVùng trán sáng sủa cho thấy tinh thần minh mẫn. Tuy nhiên, nên bổ sung omega-3 (cá hồi, hạt chia, quả óc chó) để bảo vệ sức khỏe não bộ lâu dài.',
    'Theo như tôi phân tích, các đặc điểm khuôn mặt gợi ý bạn nên chú ý đến chế độ ăn uống. Bổ sung vitamin và khoáng chất sẽ giúp cải thiện sức khỏe tổng thể.\n\nDa mặt hơi khô cho thấy cần uống nhiều nước hơn và bổ sung vitamin E. Collagen từ thực phẩm (nước hầm xương, cá) cũng rất có lợi.\n\nĐường vân trên trán ngang bằng cho thấy bạn có xu hướng lo lắng nhiều. Stress kéo dài ảnh hưởng đến dạ dày và giấc ngủ. Hãy tập thiền hoặc hít thở sâu 10 phút mỗi ngày.',
    'Sắc mặt và ánh mắt cho thấy tinh thần tốt. Hãy duy trì lối sống lành mạnh và giữ tâm trạng tích cực để sức khỏe luôn ổn định.\n\nCằm đầy đặn cho thấy sinh lực dồi dào và sức bền tốt. Bạn có thể tập luyện cường độ cao mà không dễ kiệt sức. Tuy nhiên, đừng lạm dụng — cơ thể cũng cần thời gian nghỉ ngơi.\n\nTai dày và có dái tai lớn là dấu hiệu của sức khỏe tốt và tuổi thọ cao theo tướng học. Hãy tiếp tục duy trì thói quen sống lành mạnh.',
  ],
  personality: [
    'Theo phân tích, khuôn mặt bạn phản ánh tính cách thẳng thắn, trung thực và đáng tin cậy. Bạn là người được nhiều người yêu mến và tôn trọng.\n\nÁnh mắt nhìn thẳng cho thấy sự trung thực — bạn không giỏi nói dối và cũng không thích người khác nói dối mình. Đây là phẩm chất quý giá trong cả công việc lẫn tình cảm.\n\nLông mày đậm và gọn cho thấy tính cách quyết đoán, mạnh mẽ. Bạn có quan điểm rõ ràng và dám bảo vệ ý kiến của mình. Tuy nhiên, đôi khi cần linh hoạt hơn để tránh xung đột không đáng.',
    'Đặc điểm ngũ quan cho thấy bạn là người có trí tuệ cảm xúc cao, biết cách giao tiếp và tạo ấn tượng tốt với mọi người xung quanh.\n\nĐôi mắt to với ánh nhìn ấm áp cho thấy bạn dễ dàng kết nối với mọi người. Bạn là người "đọc" được cảm xúc của người khác và biết cách phản ứng phù hợp.\n\nMiệng thường mỉm cười tự nhiên cho thấy bạn là người lạc quan và tích cực. Năng lượng tích cực này thu hút người tốt đến bên bạn và tạo ra môi trường hòa thuận.',
    'Theo như tôi phân tích, tướng mặt thể hiện sự mạnh mẽ bên ngoài nhưng dịu dàng bên trong. Bạn có khả năng lãnh đạo nhưng cũng biết lắng nghe.\n\nXương hàm vuông vừa phải cho thấy sự quyết đoán có chừng mực — đủ mạnh để lãnh đạo nhưng không đến mức cứng nhắc. Đây là sự cân bằng lý tưởng giữa sức mạnh và sự linh hoạt.\n\nĐôi tai gần đầu cho thấy bạn biết lắng nghe — không chỉ nghe bằng tai mà còn nghe bằng trái tim. Phẩm chất này giúp bạn xây dựng được mối quan hệ sâu sắc và bền vững.',
    'Khuôn mặt bạn toát lên sự tự tin và quyết đoán. Theo phân tích, đây là tố chất giúp bạn thành công trong mọi lĩnh vực.\n\nTrán cao và rộng cho thấy tư duy chiến lược — bạn nhìn xa, nghĩ rộng và lên kế hoạch kỹ lưỡng. Không phải dạng hành động bốc đồng, mà luôn có sự chuẩn bị chu đáo.\n\nSống mũi thẳng và mạnh cho thấy tính tự lập cao. Bạn không thích phụ thuộc người khác và luôn cố gắng tự mình giải quyết vấn đề. Đây là phẩm chất đáng quý nhưng cũng cần học cách chấp nhận sự giúp đỡ khi cần.',
  ],
  future: [
    'Theo như tôi phân tích, tướng mạo cho thấy giai đoạn tới sẽ rất thuận lợi. Cả tài lộc và sức khỏe đều tốt, hãy tận dụng thời cơ.\n\nTam đình cân đối cho thấy cuộc sống phát triển đều đặn qua các giai đoạn. Không có sự sụt giảm đột ngột — mọi thứ sẽ từ từ tốt hơn. Đặc biệt, hạ đình (cằm) phát triển tốt hứa hẹn tuổi già an nhàn và sung túc.\n\nCác nét tướng tổng thể cho thấy bạn thuộc dạng "hậu vận tốt" — càng về sau càng thuận lợi. Giai đoạn sau 45 tuổi sẽ là thời kỳ hưởng thụ thành quả của những nỗ lực trước đó.',
    'Tướng mặt gợi ý rằng bạn sẽ có bước ngoặt quan trọng trong sự nghiệp. Theo phân tích, quý nhân sẽ xuất hiện và hỗ trợ bạn vượt qua thử thách.\n\nÁnh mắt sáng và sống mũi mạnh cho thấy giai đoạn trung niên (35-50 tuổi) là đỉnh cao sự nghiệp. Tài chính dồi dào, vị trí xã hội cao, và gia đình hạnh phúc.\n\nLông mày dài qua mắt cho thấy tuổi thọ cao và sức khỏe bền bỉ. Bạn sẽ có đủ thời gian và năng lượng để tận hưởng thành quả mà mình đã vất vả xây dựng.',
    'Theo như tôi phân tích, tam đình cho thấy vận mệnh tương lai sáng sủa. Nửa sau cuộc đời sẽ an nhàn, sung túc và hạnh phúc.\n\nVùng nhân trung sâu và dài cho thấy phúc phần con cái tốt — con cái hiếu thảo và thành đạt, mang lại niềm vui cho bạn khi về già.\n\nCằm tròn đầy cho thấy tuổi 55+ sẽ rất thoải mái — tài chính ổn định, sức khỏe tốt, con cháu vui vẻ. Đây là phúc phần mà không phải ai cũng có được.',
    'Đặc điểm khuôn mặt cho thấy bạn sẽ ngày càng thành công theo thời gian. Tài lộc dồi dào, gia đình hạnh phúc và sức khỏe ổn định.\n\nCác đường nét khuôn mặt ngày càng rõ ràng theo tuổi tác cho thấy bạn đang "chín" dần — cả về ngoại hình lẫn nội tâm. Sự trưởng thành này thu hút cơ hội và người tốt đến bên bạn.\n\nTổng thể tướng mạo cho thấy bạn có tướng "phú quý" — không chỉ giàu về vật chất mà còn giàu về tinh thần. Cuộc sống sau này sẽ viên mãn theo đúng nghĩa.',
  ],
};

export function getRandomReading(mode: 'palm' | 'face'): Record<string, string> {
  const now = new Date();
  const baseSeed = now.getFullYear() * 10000 + (now.getMonth() + 1) * 100 + now.getDate();
  const modeSeed = mode === 'palm' ? 7 : 13;
  const rand = seededRandom(baseSeed * modeSeed + Math.floor(Math.random() * 1000));

  const pool = mode === 'palm' ? PALM_RESULTS : FACE_RESULTS;
  const pick = <T,>(arr: T[]): T => arr[Math.floor(rand() * arr.length)];

  return {
    overall: pick(pool.overall),
    love: pick(pool.love),
    career: pick(pool.career),
    health: pick(pool.health),
    personality: pick(pool.personality),
    future: pick(pool.future),
  };
}
